version: '3.9'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"  # Match Vite's default port
    depends_on:
      - backend
    networks:
      - hms_network

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/hms_db
      - REDIS_HOST=redis
    volumes:
      - ./server:/app
    depends_on:
      - mongo
      - redis
    networks:
      - hms_network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hms_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hms_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - hms_network

volumes:
  mongo_data:

networks:
  hms_network:
    driver: bridge
